### ISSUE TITLE
Error when trying to buy in AH ( and unable to buy the addon blocks it ) 

### ISSUE THREAD

**Issue by reaper666735** [Sonaza/DressUp#4] opened 2016-08-08 17:03 UTC
i hope it's only a random bug when i logged in since i never had it before ( or never used AH since latest update lol ........ ) 

basically each time i tried to click an item to but it , this showed up and unable to buy anything it really blocked the interface buttons

14x DressUp\core.lua:451: attempt to index field 'background' (a nil value)
DressUp\core.lua:451: in function `SetDressUpBackground'
DressUp\core.lua:932: in function <DressUp\core.lua:925>
(tail call): ?
(tail call): ?
...ns\Blizzard_VoidStorageUI\Blizzard_VoidStorageUI-1.0.lua:396: in function <...ns\Blizzard_VoidStorageUI\Blizzard_VoidStorageUI.lua:384>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:398
 TryOn = <function> defined @DressUp\core.lua:947
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "DressUp"
 SetDressUpBackground = <function> defined @DressUp\core.lua:449
 GetInfoForSlot = <function> defined @DressUp\core.lua:768
 SecureHookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:410
 MODIFIER_STATE_CHANGED = <function> defined @DressUp\core.lua:209
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 ShowingHelm = <function> defined @DressUp\core.lua:870
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:482
 GetRaceIndex = <function> defined @DressUp\core.lua:521
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:381
 SelectedGender = 0
 GenerateRaceMenu = <function> defined @DressUp\core.lua:627
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 hooks = <table> {
 }
 db = <table> {
 }
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 SwitchBackground = <function> defined @DressUp\core.lua:539
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:468
 RawHook = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:313
 UpdatePaperDollItemLevels = <function> defined @DressUp\core.lua:196
 OnInitialize = <function> defined @DressUp\core.lua:221
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:266
 UpdateBackgroundTexCoords = <function> defined @DressUp\core.lua:457
 PLAYER_EQUIPMENT_CHANGED = <function> defined @DressUp\core.lua:1027
 defaultModuleLibraries = <table> {
 }
 InitializeRaceMenu = <function> defined @DressUp\core.lua:677
 SelectedRace = -1
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:310
 GetItemLinkFromSource = <function> defined @DressUp\core.lua:898
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:473
 name = "DressUp"
 GetSlotItem = <function> defined @DressUp\core.lua:1015
 ResetRaceSelect = <function> defined @DressUp\core.lua:494
 orderedModules = <table> {
 }
 IsHooked = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:493
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:345
 GetInvSlot = <function> defined @DressUp\core.lua:983
 GetTransmogItemLinkFromSlot = <function> defined @DressUp\core.lua:913
 IsSlotTransmogrifiable = <function> defined @DressUp\core.lua:905
 ItemButtons = <table> {
 }
 GetItemSourceID = <function> defined @DressUp\core.lua:885
 HookScript = <function> defined @Ace3\AceHook-3.0\AceHook-3.0.lua:366
 ShowingShoulders = <function> defined @DressUp\core.lua:880
 Enable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:325
 UnregisterAllEvents = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 ShowingCloak = <function> defined @DressUp\core.lua:875
 ResetItemButtons = <function> defined @DressU

**Comment by Sonaza** [comment] 2016-08-08 17:06
Have you tried disabling the addon? I've noticed similar weird blocking errors and WoW is blaming completely random addons for it. Make sure you have updated all of your other addons as well.

If error doesn't occur after disabling it then maybe DressUp is at fault but I haven't encountered this error myself.

**Comment by reaper666735** [comment] 2016-08-08 18:30
After disabling Dressup i was able to use the AH  "buy / buyout" buttons again and ofc get my item , so unfortunately it seems to point to the addon :p ,  BUT in all fairness i have to say i still have a phew addons who are not fully up to date ( they are alpha or Beta ) and do give random Lua errors themselves , just that if i was able to use the AH normally after disabling it still does mean Dressup had more of an impact on it :p

**Comment by Bram91** [comment] 2016-08-08 18:38
We tried to reproduce the bugs on multiple WoW installations and Addon combinations but we cant reproduce it. Could you try disabling other addons and just running DressUp to see if its caused by a conflict with another addon or if DressUp is at fault?

**Comment by reaper666735** [comment] 2016-08-09 08:20
Sorry to be be bearer of bad news , but with all addons disabled ( except Dressup ofc lol ) , i still get this error , but it does seem a bit different then yesterday i think.

fresh one :

Message: Interface\AddOns\DressUp\core.lua:451: attempt to index field 'background' (a nil value)
Time: 08/09/16 10:18:20
Count: 1
Stack: Interface\AddOns\DressUp\core.lua:451: in function `SetDressUpBackground'
Interface\AddOns\DressUp\core.lua:932: in function <Interface\AddOns\DressUp\core.lua:925>
(tail call): ?
...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:273: in function`BrowseButton_OnClick'
[string "_:OnClick"]:8: in function <[string "_:OnClick"]:1>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 TryOn = <function> defined @Interface\AddOns\DressUp\core.lua:947
 EnableModule = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "DressUp"
 SetDressUpBackground = <function> defined @Interface\AddOns\DressUp\core.lua:449
 GetInfoForSlot = <function> defined @Interface\AddOns\DressUp\core.lua:768
 SecureHookScript = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:413
 MODIFIER_STATE_CHANGED = <function> defined @Interface\AddOns\DressUp\core.lua:209
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 ShowingHelm = <function> defined @Interface\AddOns\DressUp\core.lua:870
 IsEnabled = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 GetRaceIndex = <function> defined @Interface\AddOns\DressUp\core.lua:521
 DisableModule = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 GenerateRaceMenu = <function> defined @Interface\AddOns\DressUp\core.lua:627
 RegisterMessage = <function> defined @Interface\AddOns\DressUp\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Interface\AddOns\DressUp\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 hooks = <table> {
 }
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:277
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\DressUp\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 SwitchBackground = <function> defined @Interface\AddOns\DressUp\core.lua:539
 IterateModules = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 RawHook = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:316
 UpdatePaperDollItemLevels = <function> defined @Interface\AddOns\DressUp\core.lua:196
 OnInitialize = <function> defined @Interface\AddOns\DressUp\core.lua:221
 NewModule = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 UpdateBackgroundTexCoords = <function> defined @Interface\AddOns\DressUp\core.lua:457
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\DressUp\core.lua:1027
 defaultModuleLibraries = <table> {
 }
 InitializeRaceMenu = <function> defined @Interface\AddOns\DressUp\core.lua:677
 GetName = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 GetItemLinkFromSource = <function> defined @Interface\AddOns\DressUp\core.lua:898
 IterateEmbeds = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 name = "DressUp"
 GetSlotItem = <function> defined @Interface\AddOns\DressUp\core.lua:1015
 ResetRaceSelect = <function> defined @Interface\AddOns\DressUp\core.lua:494
 orderedModules = <table> {
 }
 IsHooked = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:496
 Disable = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 GetInvSlot = <function> defined @Interface\AddOns\DressUp\core.lua:983
 GetTransmogItemLinkFromSlot = <function> defined @Interface\AddOns\DressUp\core.lua:913
 IsSlot

**Comment by Bram91** [comment] 2016-08-09 08:30
Did you install the addon with the Curse client and are you on the latest available version?

If you manually installed the addon: Redownload the latest version, remove the current addon directory in Interface\Addons\ and reinstall it.

**Comment by Bram91** [comment] 2016-08-09 08:32
Based on your error information I think its unable to load the background file.

**Comment by reaper666735** [comment] 2016-08-09 08:58
i did install via the curse client ( like all my addons ) , and i'm on version 2.1.3 , what should be the latest .......

**Comment by Bram91** [comment] 2016-08-09 08:59
2.1.3 is the latest version, could you maybe delete the addon in the curse client and reinstall it?

**Comment by Sonaza** [comment] 2016-08-09 09:02
Probably isn't necessary. Debugging bugs like these just is a horrible job so if it can be avoided it's nice.

**Comment by reaper666735** [comment] 2016-08-09 09:03
ok il try to re-install it to help, i also just want to add that the addon works perfectly when using the dressing room for viewing gear in bags / banks ...... like always ( with the backgrounds all in order ) , this only seems to pop up when i use the AH window .....

**Comment by reaper666735** [comment] 2016-08-09 10:39
reinstalling the addon did not fix it i'm afraid , another fresh error ...... sorry :p ,

Message: Interface\AddOns\DressUp\core.lua:451: attempt to index field 'background' (a nil value)
Time: 08/09/16 12:37:45
Count: 1
Stack: Interface\AddOns\DressUp\core.lua:451: in function `SetDressUpBackground'
Interface\AddOns\DressUp\core.lua:932: in function <Interface\AddOns\DressUp\core.lua:925>
(tail call): ?
...ace\AddOns\Blizzard_AuctionUI\Blizzard_AuctionUI.lua:273: in function`BrowseButton_OnClick'
[string "_:OnClick"]:8: in function <[string "_:OnClick"]:1>

Locals: self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:398
 TryOn = <function> defined @Interface\AddOns\DressUp\core.lua:947
 EnableModule = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 baseName = "DressUp"
 SetDressUpBackground = <function> defined @Interface\AddOns\DressUp\core.lua:449
 GetInfoForSlot = <function> defined @Interface\AddOns\DressUp\core.lua:768
 SecureHookScript = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:413
 MODIFIER_STATE_CHANGED = <function> defined @Interface\AddOns\DressUp\core.lua:209
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:440
 defaultModuleState = true
 ShowingHelm = <function> defined @Interface\AddOns\DressUp\core.lua:870
 IsEnabled = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:482
 GetRaceIndex = <function> defined @Interface\AddOns\DressUp\core.lua:521
 DisableModule = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:381
 GenerateRaceMenu = <function> defined @Interface\AddOns\DressUp\core.lua:627
 RegisterMessage = <function> defined @Interface\AddOns\DressUp\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 UnregisterMessage = <function> defined @Interface\AddOns\DressUp\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:181
 hooks = <table> {
 }
 db = <table> {
 }
 SetEnabledState = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:277
 enabledState = true
 RegisterEvent = <function> defined @Interface\AddOns\DressUp\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:118
 SwitchBackground = <function> defined @Interface\AddOns\DressUp\core.lua:539
 IterateModules = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:468
 RawHook = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:316
 UpdatePaperDollItemLevels = <function> defined @Interface\AddOns\DressUp\core.lua:196
 OnInitialize = <function> defined @Interface\AddOns\DressUp\core.lua:221
 NewModule = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:266
 UpdateBackgroundTexCoords = <function> defined @Interface\AddOns\DressUp\core.lua:457
 PLAYER_EQUIPMENT_CHANGED = <function> defined @Interface\AddOns\DressUp\core.lua:1027
 defaultModuleLibraries = <table> {
 }
 InitializeRaceMenu = <function> defined @Interface\AddOns\DressUp\core.lua:677
 GetName = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:310
 GetItemLinkFromSource = <function> defined @Interface\AddOns\DressUp\core.lua:898
 IterateEmbeds = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:473
 name = "DressUp"
 GetSlotItem = <function> defined @Interface\AddOns\DressUp\core.lua:1015
 ResetRaceSelect = <function> defined @Interface\AddOns\DressUp\core.lua:494
 orderedModules = <table> {
 }
 IsHooked = <function> defined @Interface\AddOns\DressUp\libs\AceHook-3.0\AceHook-3.0.lua:496
 Disable = <function> defined @Interface\AddOns\DressUp\libs\AceAddon-3.0\AceAddon-3.0.lua:345
 GetInvSlot = <function> defined @Interface\AddOns\DressUp\core.lua:983
 GetTransmogItemLinkFromSlot = <function> defined @Interface\AddOns\DressUp\core.lua:913
 IsSlot

**Comment by Sonaza** [comment] 2016-08-09 10:44
I may have found the cause. You are using the side dressup panel (the option for disabling side panel is toggled off)?

Terminology you have used has sort of misled me and it's not matter of Blizzard UI blocking use of protected functions after all.

**Comment by reaper666735** [comment] 2016-08-09 10:49
yes the preview panel linked to the AH window is active ( the option to hide side panel is not checked :p ) first time it did this error tbh.

**Comment by Sonaza** [comment] 2016-08-09 11:38
Error fixed in release 2.1.4.

**Closed as completed by Sonaza** 2016-08-09 11:38 UTC

**Comment by reaper666735** [comment] 2016-08-09 11:49
i can confirm it's fixed :D , ty both for the help :)
